source: ./src
plugins:     ./src/_plugins
layouts:     ./src/_layouts
destination: ./_site
#auto:       true
highlighter: pygments

#relative_permalinks: true
# permalink:  /:categories/:year-:month-:day/:title
permalink:  none

#deploy-also change in nav.js
#baseurl:  http://www.eecs.berkeley.edu/~animesh.garg
baseurl:   /~animesh.garg
#debug
#linux
#baseurl:   /home/animesh/work/jekyll-website/_site
#Mac
#baseurl:	/Users/animesh/work/jekyll-website/_site

#markdown
markdown:    kramdown

#redcloth:
#  hard_breaks: true

#kramdown:
