source: ./src
#plugins:     ./_plugins
#layouts:     ./_layouts
destination: ./_site
#auto:       true
pygments:   true

#relative_permalinks: true
# permalink:  /:categories/:year-:month-:day/:title
permalink:  none

baseurl:   .
#baseurl:   http://www.eecs.berkeley.edu/~animesh.garg
#linux
#baseurl:   /home/animesh/work/jekyll-website/_site
#Mac
#baseurl:   /Users/animesh/work/jekyll-website/_site

redcloth:
  hard_breaks: true
